### ISSUE TITLE
CertificateSelector.Select ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by mbican** [natemcmaster/LetsEncrypt#19]
```
A 2019-09-25T21:02:02.537223113Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[0]
 
A 2019-09-25T21:02:02.537287441Z       Unhandled exception while processing 0HLQ1VD105N46.
 
A 2019-09-25T21:02:02.537293658Z System.ArgumentNullException: Value cannot be null. (Parameter 'key')
 
A 2019-09-25T21:02:02.538987949Z    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
 
A 2019-09-25T21:02:02.539008407Z    at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
 
A 2019-09-25T21:02:02.539013518Z    at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateSelector.Select(ConnectionContext features, String domainName)
 
A 2019-09-25T21:02:02.540087019Z    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.<>c__DisplayClass8_0.<InnerOnConnectionAsync>b__3(Object sender, String name)
 
A 2019-09-25T21:02:02.540103412Z    at System.Net.Security.SslStream.ServerCertSelectionCallbackWrapper(String targetHost)
 
A 2019-09-25T21:02:02.540836836Z    at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint, Byte[] clientHello)
 
A 2019-09-25T21:02:02.540851884Z    at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
 
A 2019-09-25T21:02:02.541014483Z    at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
 
A 2019-09-25T21:02:02.541023526Z    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
 
A 2019-09-25T21:02:02.541061642Z    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
 
A 2019-09-25T21:02:02.541068525Z    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
 
A 2019-09-25T21:02:02.541082491Z    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
 
A 2019-09-25T21:02:02.542738587Z    at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
 
A 2019-09-25T21:02:02.542750923Z    at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
 
A 2019-09-25T21:02:02.542803249Z    at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
 
A 2019-09-25T21:02:02.542851405Z    at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
 
A 2019-09-25T21:02:02.542921115Z    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
 
A 2019-09-25T21:02:02.542941842Z    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
 
A 2019-09-25T21:02:02.542988870Z    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
 
A 2019-09-25T21:02:02.543026813Z    at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
 
A 2019-09-25T21:02:02.543032467Z    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
 
A 2019-09-25T21:02:02.543089541Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
 
A 2019-09-25T21:02:09.473153427Z [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
 
````

**Comment by natemcmaster** [comment]
Can you share more details? A stack trace alone isn’t going to help me solve this.

**Comment by mbican** [comment]
yes, sure, it is actually from the documentation Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions.ServerCertificateSelector:

 // Summary:
        //     A callback that will be invoked to dynamically select a server certificate. This
        //     is higher priority than ServerCertificate. If SNI is not available then the name
        //     parameter will be null.
        //     If the server certificate has an Extended Key Usage extension, the usages must
        //     include Server Authentication (OID 1.3.6.1.5.5.7.3.1).
        public Func<ConnectionContext, string, X509Certificate2> ServerCertificateSelector { get; set; }

so I guess just return the defaut certificate if the name is null. The second part of documentation is that key argument in ConcurrentDictionary.TryGetValue() method cannot be null:

       //
        // Summary:
        //     Attempts to get the value associated with the specified key from the System.Collections.Concurrent.ConcurrentDictionary`2.
        //
        // Parameters:
        //   key:
        //     The key of the value to get.
        //
        //   value:
        //     When this method returns, contains the object from the System.Collections.Concurrent.ConcurrentDictionary`2
        //     that has the specified key, or the default value of the type if the operation
        //     failed.
        //
        // Returns:
        //     true if the key was found in the System.Collections.Concurrent.ConcurrentDictionary`2;
        //     otherwise, false.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     key is null.
        public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value);

**Comment by mbican** [comment]
I suppose it can be reproduced by accessing the server by https url with an ip address instead of domain name

**Comment by natemcmaster** [comment]
>  accessing the server by https url with an ip address instead of domain name

Gotcha. Thanks for clarifying! Should be very easy to fix this one.
