### ISSUE TITLE
Doesn't work on Render.com

### ISSUE THREAD

**Issue by angelsix** [natemcmaster/LetsEncrypt#32]
I have a basic ASP.Net Core website, with HTTP and HTTPS enabled and bound correctly with `.UseUrls("http://*", "https://*")` and `app.UseHsts()`. 

I add dev certs when running and testing as localhost

```
dotnet dev-certs https --clean
dotnet dev-certs https -t
```

Then I add LetsEncrypt.

```
// Automatic HTTPS cert
services.AddLetsEncrypt(c =>
{
    // Set domain names
    c.DomainNames = new[] { "mydomain.com" };

    // Email to use as the contact
    c.EmailAddress = "contact@myemail.com";

    // Auto accept LetsEncrypt terms
    c.AcceptTermsOfService = true;
});
```

Running the site through Kestrel works fine on HTTP and HTTPS (it uses the dev cert).

Running the site through Visual Studio Docker with this Dockerfile works fine on HTTP and HTTPS works fine (it uses LetsEncrypt cert) NOTE: I have my dev machine pointed to via a website like mywebsite.com so I can do https://mywebsite.com and it points to this machine and the docker instance gets hit up. Hitting up HTTP localhost is fine, but HTTPS localhost doesn't (to be expected and not an issue).

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Server.csproj", ""]
RUN dotnet restore "./Server.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Server.dll"]
```

Running the site through docker directly with `docker build -t myproject .` then `docker run --rm -it -p 80:80 -p 443:443 myproject -name myproject` also works in exactly the same way. 

Finally, the issue comes when I then deploy this exact site to Render.com. I just update the domain name in the LetsEncrypt config to point to the render URL that the docker is available at such as `myproject.onrender.com`. When I deploy it I get the warning `Invalid response from https://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU [34.83.64.96]: 404, Code = Forbidden` Here is the full log

```
Dec 21 01:59:19 PM  ==> Checking out commit 6ffa57e7b66eb9967001c2a14817952716435bf2 in branch master
Dec 21 01:59:21 PM  INFO[0000] Using dockerignore file: /opt/render/project/src/Website/ServerRoot/.dockerignore
Dec 21 01:59:21 PM  INFO[0000] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
Dec 21 01:59:23 PM  INFO[0002] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
Dec 21 01:59:24 PM  INFO[0002] Downloading base image mcr.microsoft.com/dotnet/core/sdk:3.1-buster
Dec 21 01:59:24 PM  INFO[0003] Downloading base image mcr.microsoft.com/dotnet/core/sdk:3.1-buster
Dec 21 01:59:25 PM  INFO[0003] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
Dec 21 01:59:25 PM  INFO[0004] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
Dec 21 01:59:26 PM  INFO[0004] WORKDIR /app
Dec 21 01:59:26 PM  INFO[0004] Changed working directory to /app
Dec 21 01:59:26 PM  INFO[0004] Creating directory /app
Dec 21 01:59:26 PM  INFO[0004] EXPOSE 80
Dec 21 01:59:26 PM  INFO[0004] EXPOSE 443
Dec 21 01:59:27 PM  INFO[0006] Deleting filesystem...
Dec 21 01:59:27 PM  INFO[0006] Downloading base image mcr.microsoft.com/dotnet/core/sdk:3.1-buster
Dec 21 01:59:27 PM  INFO[0006] Downloading base image mcr.microsoft.com/dotnet/core/sdk:3.1-buster
Dec 21 01:59:48 PM  INFO[0026] WORKDIR /src
Dec 21 01:59:48 PM  INFO[0026] Changed working directory to /src
Dec 21 01:59:48 PM  INFO[0026] Creating directory /src
Dec 21 01:59:48 PM  INFO[0026] COPY ["Server.csproj", ""]
Dec 21 01:59:48 PM  INFO[0026] RUN dotnet restore "./Server.csproj"
Dec 21 02:00:04 PM  INFO[0042] COPY . .
Dec 21 02:00:04 PM  INFO[0042] WORKDIR "/src/."
Dec 21 02:00:04 PM  INFO[0042] Changed working directory to /src
Dec 21 02:00:04 PM  INFO[0042] RUN dotnet build "Server.csproj" -c Release -o /app/build
Dec 21 02:00:04 PM  Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Dec 21 02:00:04 PM  Copyright (C) Microsoft Corporation. All rights reserved.
Dec 21 02:00:04 PM  
Dec 21 02:00:05 PM    Restore completed in 54.83 ms for /src/Server.csproj.
Dec 21 02:00:05 PM    Restore completed in 17.89 ms for /src/Server.csproj.
Dec 21 02:00:08 PM    Server -> /app/build/Server.dll
Dec 21 02:00:08 PM  
Dec 21 02:00:08 PM  Build succeeded.
Dec 21 02:00:08 PM      0 Warning(s)
Dec 21 02:00:08 PM      0 Error(s)
Dec 21 02:00:08 PM  
Dec 21 02:00:08 PM  Time Elapsed 00:00:04.14
Dec 21 02:00:27 PM  INFO[0065] Deleting filesystem...
Dec 21 02:00:29 PM  INFO[0067] Base image from previous stage 1 found, using saved tar at path /kaniko/stages/1
Dec 21 02:01:01 PM  INFO[0100] RUN dotnet publish "Server.csproj" -c Release -o /app/publish
Dec 21 02:01:02 PM  Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Dec 21 02:01:02 PM  Copyright (C) Microsoft Corporation. All rights reserved.
Dec 21 02:01:02 PM  
Dec 21 02:01:03 PM    Restore completed in 50.01 ms for /src/Server.csproj.
Dec 21 02:01:03 PM    Restore completed in 88.34 ms for /src/Server.csproj.
Dec 21 02:01:06 PM    Server -> /src/bin/Release/netcoreapp3.1/Server.dll
Dec 21 02:01:06 PM    Server -> /app/publish/
Dec 21 02:01:13 PM  INFO[0111] Saving file /app/publish for later use.
Dec 21 02:01:13 PM  INFO[0111] Deleting filesystem...
Dec 21 02:01:15 PM  INFO[0114] Base image from previous stage 0 found, using saved tar at path /kaniko/stages/0
Dec 21 02:01:16 PM  INFO[0114] WORKDIR /app
Dec 21 02:01:16 PM  INFO[0114] Changed working directory to /app
Dec 21 02:01:16 PM  INFO[0114] Creating directory /app
Dec 21 02:01:16 PM  INFO[0114] COPY --from=publish /app/publish .
Dec 21 02:01:16 PM  INFO[0115] ENTRYPOINT ["dotnet", "Server.dll"]
Dec 21 02:01:18 PM   ______________________________
Dec 21 02:01:18 PM  < Pushing image to registry... >
Dec 21 02:01:18 PM   ------------------------------
Dec 21 02:01:18 PM          \   ^__^
Dec 21 02:01:18 PM           \  (oo)\_______
Dec 21 02:01:18 PM              (__)\       )\/\
Dec 21 02:01:18 PM                  ||----w |
Dec 21 02:01:18 PM                  ||     ||
Dec 21 02:01:22 PM   ______
Dec 21 02:01:22 PM  < Done >
Dec 21 02:01:22 PM   ------
Dec 21 02:01:22 PM          \   ^__^
Dec 21 02:01:22 PM           \  (oo)\_______
Dec 21 02:01:22 PM              (__)\       )\/\
Dec 21 02:01:22 PM                  ||----w |
Dec 21 02:01:22 PM                  ||     ||
Dec 21 02:01:29 PM  warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
Dec 21 02:01:29 PM        Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Dec 21 02:01:29 PM  info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Dec 21 02:01:29 PM        User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Dec 21 02:01:29 PM  info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
Dec 21 02:01:29 PM        Creating key {3b6e2d17-c695-4572-817f-9b2f88230846} with creation date 2019-12-21 14:01:29Z, activation date 2019-12-21 14:01:29Z, and expiration date 2020-03-20 14:01:29Z.
Dec 21 02:01:29 PM  warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
Dec 21 02:01:29 PM        No XML encryptor configured. Key {3b6e2d17-c695-4572-817f-9b2f88230846} may be persisted to storage in unencrypted form.
Dec 21 02:01:29 PM  info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
Dec 21 02:01:29 PM        Writing data to file '/root/.aspnet/DataProtection-Keys/key-3b6e2d17-c695-4572-817f-9b2f88230846.xml'.
Dec 21 02:01:29 PM  Hosting environment: Production
Dec 21 02:01:29 PM  Content root path: /app
Dec 21 02:01:29 PM  Now listening on: http://[::]:80
Dec 21 02:01:29 PM  Now listening on: https://[::]:443
Dec 21 02:01:29 PM  Application started. Press Ctrl+C to shut down.
Dec 21 02:01:30 PM  info: McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader[0]
Dec 21 02:01:30 PM        Creating certificate registration for contact@angelsix.com
Dec 21 02:01:31 PM  info: McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader[0]
Dec 21 02:01:31 PM        Creating certificate for myproject.onrender.com using ACME server https://acme-v02.api.letsencrypt.org/directory
Dec 21 02:01:33 PM  fail: McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader[0]
Dec 21 02:01:33 PM        Failed to validate ownership of domainName 'myproject.onrender.com'. Reason: urn:ietf:params:acme:error:unauthorized: Invalid response from https://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU [34.83.64.96]: 404, Code = Forbidden
Dec 21 02:01:33 PM  fail: McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader[0]
Dec 21 02:01:33 PM        Failed to automatically create a certificate for myproject.onrender.com
Dec 21 02:01:33 PM  System.InvalidOperationException: Failed to validate ownership of domainName 'myproject.onrender.com'
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.GetOrCreateCertificate(CertificateFactory factory, CancellationToken cancellationToken)
Dec 21 02:01:33 PM  fail: McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader[0]
Dec 21 02:01:33 PM        Failed to create certificate
Dec 21 02:01:33 PM  System.InvalidOperationException: Failed to validate ownership of domainName 'myproject.onrender.com'
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.GetOrCreateCertificate(CertificateFactory factory, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.LoadCerts(CancellationToken cancellationToken)
```

Any ideas why? Even if you actually hit up the URL Invalid response from https://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU it does work and does return the value it should. So it's almost like when inside render inside a Docker that its own URL isn't available maybe?

**Comment by angelsix** [comment]
Also after this failure, if I shell into the docker and run the command it fails with, it works fine and fetches (note IP and details altered to prevent any sensitive data showing)

```
# wget  https://www.mydomain.com/.well-known/acme-challenge/Abrz3x1JWQxL2huhfE9G5mEauP1L-oQb0PvIh-uAaOI
Resolving www.mydomain.com ... IP REMOVED
Connecting to www.mydomain.com|IPREMOVED:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87 [application/octet-stream]
Saving to: 'Abrz3x1JWQxL2huhfE9G5mEauP1L-oQb0PvIh-uAaOI'

Abrz3x1JWQxL2huhfE9G5mEauP1L-oQb0PvIh-uAaOI       100%[===========================================================================================================>]      87  --.-KB/s    in 0s      

2019-12-21 15:28:48 (98.4 MB/s) - 'Abrz3x1JWQxL2huhfE9G5mEauP1L-oQb0PvIh-uAaOI' saved [87/87]
```

**Comment by natemcmaster** [comment]
Something is cause a HTTPS redirect before the ACME domain validation middleware can respond. 
```
$ curl 'http://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU' --verbose --insecure

> GET /.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU HTTP/1.1
> Host: www.myproject.onrender.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: https://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU
< Date: Sat, 21 Dec 2019 19:46:29 GMT
< Content-Length: 140
<
<a href="https://www.myproject.onrender.com/.well-known/acme-challenge/s70hNUxmZ7vrfcYC2RxpqbOiAKYEBupuVO00aaJEkgU">Moved Permanently</a>.
```
Can you tell me more about your hosting environment? Who is the hosting provider? Is Kestrel actually doing the SSL termination, or is it running behind a reverse proxy? 

I'm just guessing, but it seems like your site is running behind another server which is doing the SSL termination, which is not a scenario this library can support. The HTTPS certificate shows a valid Let's Encrypt certificate already configured, but it's using a wildcard certificate which this library doesn't support generating (#1).

![image](https://user-images.githubusercontent.com/2696087/71313145-a02edf80-23e9-11ea-9b33-342c81acff9d.png)

By the way, that site is misconfigured. Wildcard certs are only good for one-level of subdomain, so myproject.onrender.com is okay, but www.myproject.onrender.com is not. See https://www.instantssl.com/multi-level-wildcard more details about this.

**Comment by angelsix** [comment]
The site URL is not the actual site I just changed it to any name to hide the real site. I've emailed you the real site to investigate

**Comment by natemcmaster** [comment]
Render.com is a hosting provider which appears to offer free HTTPS for you. They would be implementing that via reverse proxy which will forward traffic to your app unencrypted. I don't think you need to worry about certificate configuration or HTTPS redirection. It appears their front end is doing the SSL termination for you.

If you need more help, I recommend contacting render.com support.
