### ISSUE TITLE
Why can't it validate the ownership of my domain?

### ISSUE THREAD

**Issue by Kayuwaii** [natemcmaster/LetsEncrypt#63]
I can't seem to get this to work. It uses the default certificate. I checked the logs and found this:
```
2020-04-06 13:17:28.907 +02:00 [Information] Starting web host
2020-04-06 13:17:30.180 +02:00 [Information] User profile is available. Using '"C:\Users\alexcoratl\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2020-04-06 13:17:30.245 +02:00 [Debug] Using the ASP.NET Core HTTPS development certificate for 'localhost' requests
2020-04-06 13:17:30.611 +02:00 [Information] Now listening on: "https://[::]:5001"
2020-04-06 13:17:30.611 +02:00 [Information] Now listening on: "http://[::]:5000"
2020-04-06 13:17:30.612 +02:00 [Information] Application started. Press Ctrl+C to shut down.
2020-04-06 13:17:30.612 +02:00 [Information] Hosting environment: "Development"
2020-04-06 13:17:30.612 +02:00 [Information] Content root path: "E:\Documentos\Cosprea\Cosprea\Cosprea.API"
2020-04-06 13:17:31.506 +02:00 [Debug] Terms of service has been accepted
2020-04-06 13:17:31.506 +02:00 [Information] Creating certificate registration for "alexcoralt@msn.com"
2020-04-06 13:17:32.119 +02:00 [Information] Creating certificate for "cosprea.ml" using ACME server https://acme-v02.api.letsencrypt.org/directory
2020-04-06 13:17:32.738 +02:00 [Debug] Requesting authorization to create certificate for "cosprea.ml"
2020-04-06 13:17:32.937 +02:00 [Debug] Requesting completion of challenge to prove ownership of domain "cosprea.ml"
2020-04-06 13:17:35.501 +02:00 [Error] Failed to validate ownership of domainName '"cosprea.ml"'. Reason: "urn:ietf:params:acme:error:unauthorized: Invalid response from https://cosprea.ml/.well-known/acme-challenge/nxgP1SkXj9vXDw_AOAb-s6JC4hfHqYyd9J-Vy9nDcY8 [81.184.30.169]: \"<!DOCTYPE HTML PUBLIC \\"-//IETF//DTD HTML 2.0//EN\\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p\", Code = Forbidden"
2020-04-06 13:17:35.503 +02:00 [Error] Failed to automatically create a certificate for "cosprea.ml"
System.InvalidOperationException: Failed to validate ownership of domainName 'cosprea.ml'
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.GetOrCreateCertificate(CertificateFactory factory, CancellationToken cancellationToken)
2020-04-06 13:17:35.552 +02:00 [Error] Failed to create certificate
System.InvalidOperationException: Failed to validate ownership of domainName 'cosprea.ml'
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.CertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.GetOrCreateCertificate(CertificateFactory factory, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.LoadCerts(CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.Internal.AcmeCertificateLoader.<>c__DisplayClass12_0.<<StartAsync>b__0>d.MoveNext()
```
Any idea about what to change?

**Comment by Kayuwaii** [comment]
Nevermind, it was a dns issue

**Comment by Tomi-15** [comment]
How did you solve it?

**Comment by Kayuwaii** [comment]
I didn't, i actually ended up relying  on compiling and runing on the webserver under the same domain and site. Therefore using the same TLS certificate.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tomi-15** [comment]
I don't understand. Can you explain?

**Comment by Tomi-15** [comment]
I get this error :
`Apr 18 20:51:51 prestaservi.net dotnet-example[6746]: [20:51:51 DBG] Confirmed challenge request for GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg
Apr 18 20:51:51 prestaservi.net dotnet-example[6746]: [20:51:51 DBG] Confirmed challenge request for GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg
Apr 18 20:51:53 prestaservi.net dotnet-example[6746]: [20:51:53 ERR] Failed to validate ownership of domainName 'prestaservi.net'. Reason: urn:ietf:params:acme:error:connection: Fetching http://prestaservi.net/.well-known/acme-challenge/zt1_DaK9LlMgueAyn4FNAOKLABFX_mi02lQTWEhx9aI: Connection refused, Code = BadRequest
Apr 18 20:51:53 prestaservi.net dotnet-example[6746]: [20:51:53 ERR] Failed to validate ownership of domainName 'www.prestaservi.net'. Reason: urn:ietf:params:acme:error:connection: During secondary validation: Fetching http://www.prestaservi.net/.well-known/acme-challenge/GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg: Connection refused, Code = BadRequest`

**Comment by Kayuwaii** [comment]
Since it didn’t validate I just resorted to using the same site and TLS certifiate and not using Let’s encrypt

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Tomas<mailto:notifications@github.com>
Enviado: domingo, 19 de abril de 2020 0:00
Para: natemcmaster/LetsEncrypt<mailto:LetsEncrypt@noreply.github.com>
CC: Alex Coronas<mailto:alexcoralt@msn.com>; State change<mailto:state_change@noreply.github.com>
Asunto: Re: [natemcmaster/LetsEncrypt] Why can't it validate the ownership of my domain? (#63)


I don't understand. Can you explain?

**Comment by Kayuwaii** [comment]
Do you have your domain redirected to the proper address? It seems to be failing to conect or getting some code 500 responses

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Tomas<mailto:notifications@github.com>
Enviado: domingo, 19 de abril de 2020 0:01
Para: natemcmaster/LetsEncrypt<mailto:LetsEncrypt@noreply.github.com>
CC: Alex Coronas<mailto:alexcoralt@msn.com>; State change<mailto:state_change@noreply.github.com>
Asunto: Re: [natemcmaster/LetsEncrypt] Why can't it validate the ownership of my domain? (#63)


I get this error :
Apr 18 20:51:51 prestaservi.net dotnet-example[6746]: [20:51:51 DBG] Confirmed challenge request for GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg Apr 18 20:51:51 prestaservi.net dotnet-example[6746]: [20:51:51 DBG] Confirmed challenge request for GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg Apr 18 20:51:53 prestaservi.net dotnet-example[6746]: [20:51:53 ERR] Failed to validate ownership of domainName 'prestaservi.net'. Reason: urn:ietf:params:acme:error:connection: Fetching http://prestaservi.net/.well-known/acme-challenge/zt1_DaK9LlMgueAyn4FNAOKLABFX_mi02lQTWEhx9aI: Connection refused, Code = BadRequest Apr 18 20:51:53 prestaservi.net dotnet-example[6746]: [20:51:53 ERR] Failed to validate ownership of domainName 'www.prestaservi.net'. Reason: urn:ietf:params:acme:error:connection: During secondary validation: Fetching http://www.prestaservi.net/.well-known/acme-challenge/GIf5_w2zI80eTzMBnBYTHr7fu0hjHVxOLmefkKQGKbg: Connection refused, Code = BadRequest

**Comment by Tomi-15** [comment]
Yes, my domain points to my server's ip. I also added a middleware of UseStaticFiles that points to a folder called `.well-known` that is located on the server root directory

**Comment by Tomi-15** [comment]
Maybe you have to know that my ASPNET core server uses 80 and 443 ports because I don't use a reverse proxy. Maybe that's why when the URL requests mydomain.com/.well-known asp.net kestrel is who manages it. But I added a static file provider to that folder
